name: Make Readme

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Making Readme
      run: |
        utils/make_readme.py -o No
    - name: Commit new Readme
      run: |
        if git diff --exit-code ; then
          echo "No changes to commit."
          exit 0
        else
          git config user.name github-actions
          git config user.emal github-actions@github.com
          git add README.md
          git commit -m "updating README.md"
          git push origin
        fi
