name: Make Readme

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Making Readme
      run: |
        python utils/make_readme.py
    - uses: stefanweifel/git-auto-commit-action@v5
      with:
        commit_message: Update Readme
        file_pattern: 'README.md'
        
