name: Make Readme

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Making Readme
      run: |
        utils/make_readme.py -o No
    - name: Check for changes
      run: |
        ! git diff --quiet
    - name: Commit new Readme
      if: ${{ success() }}
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "updating README.md"
          git push origin
